version: "3.5"
networks:
    react-app-network:
        name: react-app-network
services:
    nginx:
        container_name: react-app-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/dist:/var/www/react-app
        ports:
            - 8090:80
        networks:
            - react-app-network

    react-app:
        container_name: react-app
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        command: "bash -c 'yarn && yarn run build'"
        networks:
            - react-app-network
