version: "3.5"
networks:
    react-app-network:
        name: react-app-network
services:
    react-app:
        container_name: react-app
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - "8080:8080"
        command: "bash -c 'yarn && yarn run dev-docker'"
        networks:
            - react-app-network
